env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - import
  - '@typescript-eslint'
rules:
  import/prefer-default-export: off
  max-len: off
overrides:
  - files:
      - '*.ts'
    rules:
      no-console:
        - 1
      # fix issue where interfaces and types are "unused"
      '@typescript-eslint/no-unused-vars':
        - 2
        - args: none
